# Generated by Django 2.2.4 on 2019-08-30 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20190830_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
