# Generated by Django 2.2.4 on 2019-08-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
