# Generated by Django 2.2.4 on 2019-08-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20190830_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
